[package]
name = "finite_element_method_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
gauss-quad = "0.1.8"
plotters = "0.3.5"